name: 'Quality Check & Bump Version'

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  quality-check:
    name: 'Quality Check & Bump Version'
    runs-on: ubuntu-latest
    if: !startsWith(github.event.head_commit.message, 'v')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn test

  create-release:
    name: 'Bump Version'
    runs-on: ubuntu-latest
    needs: quality-check
    if: github.event_name == 'push'

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
          ssh-key: ${{ secrets.BUMP_SECRET }}

      - run: cat ./package.json

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BUMP_SECRET }}
          known_hosts: github.com

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: v
          skip-push: true

      - run: git push origin ${{ github.ref_name }} --tags

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: Release ${{ github.event.head_commit.message }}
          body: ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - run: cat ./package.json

      - name: Output Step
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"