name: 'Quality Check & Bump Version'

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  bump-version:
    name: 'Quality Check & Bump Version'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}

      - run: cat ./package.json

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org/

      - run: yarn install --frozen-lockfile
      - run: yarn test

      - name: 'Automated Version Bump'
        if: ${{ github.event == 'push' }}
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ github.event == 'push' }}
        run: cat ./package.json

      - if: ${{ github.event == 'push' }}
        name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
